<?php
    echo '<h1>Задача 1. Get product by ID, SKU. Использовать DI.</h1>';

    $product_id = $block->getProductById(4);
    echo 'ID: ' . $product_id->getId() . '<br>';
    echo 'Name: ' . $product_id->getName() . '<br>';

    echo '<br>';

    $product_sku = $block->getProductBySku('24-MB05');
    echo 'SKU: ' . $product_sku->getSku() . '<br>';
    echo 'Name: ' . $product_sku->getName() . '<br>';
?>