<?php
    echo '<h1>Тестовое задание 3</h1>';

    echo '<h2>3.1 Получить коллекцию Bundle products и к каждому такому продукту получить список Children Products</h2>';
    $bundleCollection = $block->getBundleProducts();
    foreach ($bundleCollection as $bundle) {
        echo '<h3>' . $bundle->getName() . '</h3>';  
        $typeInstance = $bundle->getTypeInstance();   
        $childrenIds = $typeInstance->getChildrenIds($bundle->getId(), true); 
        foreach($childrenIds as $childrenKey => $childrenValue) {
            foreach ($childrenValue as $key => $value) {
                echo '- ' . $block->getProductById($value)->getName() . '<br>';
            }
        }
    }   

    echo '<h2>3.2 Получить коллекцию Grouped products и к каждому такому продукту получить список Children Products</h2>';
    $groupedCollection = $block->getGroupedProducts();
    foreach ($groupedCollection as $grouped) {
        echo '<h3>' . $grouped->getName() . '</h3>';  
        $typeInstance = $grouped->getTypeInstance();   
        $childrenIds = $typeInstance->getChildrenIds($grouped->getId(), true); 
        foreach($childrenIds as $childrenKey => $childrenValue) {
            foreach ($childrenValue as $key => $value) {
                echo '- ' . $block->getProductById($value)->getName() . '<br>';
            }
        }
    }
?>