<?php
    echo '<h1>Тестовое задание 2</h1>';
    echo '<h2>На новой странице вывести SKU, Name и Price продуктов <br>из категории Women - Tops - Jackets, где Price от 50$ до 60$</h2>';
    
    echo '<h3>Вывод через список: </h3>';
    $viewModel = $block->getData('view_model');
    $productCollection = $viewModel->getProductCollection();
    foreach ($productCollection as $product) {
        echo 'Name: ' . $product->getName() . '<br>';   
        echo 'Price: ' . $product->getPrice() . '<br>';   
        echo 'SKU: ' . $product->getSku() . '<br><br>';   
    }    

    echo '<h3>Вывод через таблицу: </h3>';
    echo '<table border="1">';
    echo '<tr>';
        echo '<th>Name</th>';
        echo '<th>Price</th>';
        echo '<th>Sku</th>';
    echo '</tr>';
    foreach ($productCollection as $product) {
        echo '<tr>';
            echo '<td>' . $product->getName() . '</td>';
            echo '<td>' . $product->getPrice() . '</td>';
            echo '<td>' . $product->getSku() . '</td>';
        echo '</tr>';
    }
    echo '</table>';
?>