<?php
    $cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
    $titleHtml = '';
    if (trim($block->getPageHeading())) {
        $titleHtml = '<span class="base" data-ui-id="page-title-wrapper" '
            . $block->getAddBaseAttribute()
            . '><i>'
            . $block->escapeHtml($block->getPageHeading())
            . '</i></span>';
    }
?>
<?php if ($titleHtml) : ?>
    <div class="page-title-wrapper<?= $block->escapeHtmlAttr($cssClass) ?>">
        <h1 class="page-title"
            <?php if ($block->getId()) : ?> id="<?= $block->escapeHtmlAttr($block->getId()) ?>" <?php endif; ?>
            <?php if ($block->getAddBaseAttributeAria()) : ?>
                aria-labelledby="<?= $block->escapeHtmlAttr($block->getAddBaseAttributeAria()) ?>"
            <?php endif; ?>>
            <?= $titleHtml ?>
        </h1>
        <?= $block->getChildHtml() ?>
    </div>
<?php endif; ?>