<style>
    .buttonImageInPopup
    {
        background-image: none;
        background: #1979c3;
        border: 1px solid #1979c3;
        color: #fff;
        cursor: pointer;
        display: inline-block;
        font-family: 'Open Sans','Helvetica Neue',Helvetica,Arial,sans-serif;
        font-weight: 600;
        box-sizing: border-box;
        vertical-align: middle;
        line-height: 2.2rem;
        padding: 14px 17px;
        font-size: 1.8rem;
        margin-bottom: 15px;
        width: 49%;
        border-radius: 3px;
    }
</style>

<input id="popup-button-iip" class="buttonImageInPopup" type="button" value="Product Image">

<div id="popup-modal-iip" style="display:none;">
    <?php $productId = $block->getCurrentProduct()->getId(); ?>
    <?= /* @noEscape */ $block->escapeHtmlAttr(__('Product Name: ')); ?>
    <?= /* @noEscape */ $block->getProductName($productId); echo '<br>'; ?>
    <?= /* @noEscape */ $block->escapeHtmlAttr(__('Product Image: ')); echo '<br>'; ?>
    <?= /* @noEscape */ $block->getProductImage($productId); ?>
</div>

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Product Image',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal-iip'));
            $("#popup-button-iip").on('click',function(){ 
                $("#popup-modal-iip").modal("openModal");
            });

        }
    );
</script>